// src/lib/designTokens.ts
import type React from 'react';

export const T = {
  MONO:  "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
  SERIF: "var(--font-playfair), 'Playfair Display', Georgia, serif",
  BODY:  "var(--font-dm-sans), 'DM Sans', system-ui, sans-serif",
} as const;

export const C = {
  BG:           '#020204',
  SURFACE:      '#07080d',
  ELEVATED:     '#0c0d14',
  BORDER:       '#1c1c26',
  BORDER_FAINT: '#0f1118',
  TEXT:         '#e2e2ec',
  TEXT2:        '#5a5a75',
  TEXT3:        '#2a2a3a',
  CYAN:         '#00e5ff',
  GREEN:        '#00ff88',
  RED:          '#ef4444',
  ORANGE:       '#f97316',
  VIOLET:       '#7c3aed',
  GOLD:         '#fbbf24',
  UP:           '#00ff88',
  DOWN:         '#ef4444',
  NEUTRAL:      '#5a5a75',
} as const;

export const S = {
  NAV_H:    '48px',
  TICKER_H: '32px',
  SIDEBAR_W:'220px',
} as const;

export const styles = {
  sectionLabel: {
    fontFamily:    "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:      '10px',
    color:         '#2a2a3a',
    letterSpacing: '0.2em',
    textTransform: 'uppercase' as const,
    marginBottom:  '16px',
  },
  insightBox: {
    background:  '#07080d',
    borderLeft:  '3px solid #00e5ff',
    padding:     '18px 22px',
    marginTop:   '16px',
  },
  insightLabel: {
    fontFamily:    "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:      '9px',
    color:         '#2a2a3a',
    letterSpacing: '0.2em',
    textTransform: 'uppercase' as const,
    marginBottom:  '8px',
  },
  insightText: {
    fontFamily: "var(--font-dm-sans), 'DM Sans', system-ui, sans-serif",
    fontSize:   '13px',
    color:      '#5a5a75',
    lineHeight: 1.7,
  },
  card: {
    background:   '#07080d',
    border:       '1px solid #1c1c26',
    padding:      '28px',
    marginBottom: '20px',
  },
  statRowLabel: {
    fontFamily: "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:   '11px',
    color:      '#5a5a75',
  },
  statRowHint: {
    fontFamily: "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:   '10px',
    color:      '#2a2a3a',
    marginTop:  '2px',
  },
  statRowValue: {
    fontFamily: "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:   '12px',
    color:      '#e2e2ec',
    fontWeight: 600,
  },
  metricLabel: {
    fontFamily:    "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:      '10px',
    color:         '#2a2a3a',
    letterSpacing: '0.15em',
    textTransform: 'uppercase' as const,
    marginBottom:  '10px',
  },
  metricValue: {
    fontFamily:   "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontWeight:   700,
    color:        '#e2e2ec',
    lineHeight:   1,
    marginBottom: '8px',
  },
  badge: (color: string) => ({
    display:       'inline-block' as const,
    fontFamily:    "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:      '10px',
    padding:       '3px 10px',
    color,
    background:    color + '18',
    border:        `1px solid ${color}30`,
    letterSpacing: '0.08em',
  }),
  tooltipStyle: {
    contentStyle: {
      background: '#0c0d14',
      border:     '1px solid #1c1c26',
      fontFamily: "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
      fontSize:   '11px',
      color:      '#e2e2ec',
    },
    labelStyle: { color: '#5a5a75', marginBottom: '4px' },
    cursor:     { stroke: '#1c1c26' },
  },
  collapsibleBtn: {
    background:    'transparent',
    border:        'none',
    color:         '#2a2a3a',
    fontFamily:    "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:      '10px',
    letterSpacing: '0.1em',
    cursor:        'pointer',
    padding:       '12px 0 0',
    display:       'flex'   as const,
    alignItems:    'center' as const,
    gap:           '6px',
  },
  collapsibleContent: {
    marginTop:  '10px',
    padding:    '14px 18px',
    background: '#0c0d14',
    border:     '1px solid #1c1c26',
    fontFamily: "var(--font-dm-sans), 'DM Sans', system-ui, sans-serif",
    fontSize:   '13px',
    color:      '#5a5a75',
    lineHeight: 1.7,
  },
  navItem: (active: boolean): React.CSSProperties => ({
    display:        'flex',
    alignItems:     'center',
    gap:            '12px',
    padding:        '12px 20px',
    fontFamily:     "var(--font-ibm-plex-mono), 'IBM Plex Mono', 'Courier New', monospace",
    fontSize:       '10px',
    letterSpacing:  '0.12em',
    textTransform:  'uppercase',
    textDecoration: 'none',
    color:          active ? '#00e5ff' : '#5a5a75',
    background:     active ? 'rgba(0,229,255,0.05)' : 'transparent',
    borderLeft:     active ? '3px solid #00e5ff' : '3px solid transparent',
    transition:     'color 0.15s',
  }),
};
